"""empty message

Revision ID: 0f04caecd31e
Revises: 
Create Date: 2023-12-11 17:43:09.871924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f04caecd31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raccoons_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trashcans_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('raccoon_id', sa.Integer(), nullable=True),
    sa.Column('trashcan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raccoon_id'], ['raccoons_table.id'], name=op.f('fk_visits_table_raccoon_id_raccoons_table')),
    sa.ForeignKeyConstraint(['trashcan_id'], ['trashcans_table.id'], name=op.f('fk_visits_table_trashcan_id_trashcans_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits_table')
    op.drop_table('trashcans_table')
    op.drop_table('raccoons_table')
    # ### end Alembic commands ###
